; PlatformIO Project Configuration File
; T3 — Supervisório de Semáforos (Saturnino de Brito x Protásio Alves)

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    knolleary/PubSubClient@^2.8
    xreef/PCF8574 library@^2.4.0
